apiVersion: v1
kind: Template
metadata:
  annotations:
    description: This template creates a pipelie to pre-build coolstore images in a builder project
  name: coolstore-imagebuild-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: coolstore-imagebuild-pipeline
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
  spec:
    triggers:
      - type: GitHub
        github:
          secret: wDmoEUkbBp
      - type: Generic
        generic:
          secret: wDmoEUkbBp
    runPolicy: SerialLatestOnly
    source:
      type: None
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        env:
        - name: GITHUB_ACCOUNT
          value: ${GITHUB_ACCOUNT}
        - name: GITHUB_REF
          value: ${GITHUB_REF}
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        jenkinsfile: >-
          node {
            stage('Update Build Configs') {
              sh "oc process -f https://raw.githubusercontent.com/${env.GITHUB_ACCOUNT}/coolstore-microservice/${env.GITHUB_REF}/openshift/templates/coolstore-builds-template.yaml --param=GIT_URI=https://github.com/${env.GITHUB_ACCOUNT}/coolstore-microservice.git --param=GIT_REF=${env.GITHUB_REF} --param=MAVEN_MIRROR_URL=${env.MAVEN_MIRROR_URL} | oc create -f - || true"
              sh "oc process -f https://raw.githubusercontent.com/${env.GITHUB_ACCOUNT}/coolstore-microservice/${env.GITHUB_REF}/openshift/templates/coolstore-builds-template.yaml --param=GIT_URI=https://github.com/${env.GITHUB_ACCOUNT}/coolstore-microservice.git --param=GIT_REF=${env.GITHUB_REF} --param=MAVEN_MIRROR_URL=${env.MAVEN_MIRROR_URL} | oc replace -f - || true"
            }
            
            stage('Build Images') {
              def buildconfigs = ['web-ui', 'inventory', 'cart', 'catalog', 'coolstore-gw', 'pricing', 'rating', 'review']
              for (bc in buildconfigs) {
                  sh "oc start-build ${bc}"
                  sleep 60
              }
            }
          }
parameters:
- displayName: GitHub Account
  name: GITHUB_ACCOUNT
  required: true
  value: jbossdemocentral
- displayName: Git Branch/Tag
  name: GITHUB_REF
  required: true
<<<<<<< HEAD
  value: master
=======
  value: stable-ocp-3.7
>>>>>>> upstream/stable-ocp-3.7
- description: Maven mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/content/groups/public/)
  displayName: Maven mirror url
  name: MAVEN_MIRROR_URL
  required: true